# Generated by Django 3.2.7 on 2021-09-25 19:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=3)),
                ('currency_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='Email address')),
                ('first_name', models.CharField(max_length=50, verbose_name='First name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last name')),
                ('dob', models.DateField(null=True, verbose_name='Date of birth')),
                ('date_joined', models.DateField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PolicyStatusMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='QuoteStatusMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policytype', models.CharField(max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='insure_app.customer')),
                ('quote_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='insure_app.quotestatusmaster')),
            ],
        ),
        migrations.CreateModel(
            name='PolicyMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policytype', models.CharField(max_length=50)),
                ('base_premium', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('agefactor', models.PositiveIntegerField()),
                ('terms_and_conditions', models.TextField()),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insure_app.currencymaster')),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateTimeField()),
                ('premium', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('max_insured_amount', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insure_app.currencymaster')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='insure_app.customer')),
                ('policy_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='insure_app.policymaster')),
                ('policy_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insure_app.policystatusmaster')),
            ],
        ),
    ]
