# Generated by Django 3.2.7 on 2021-09-25 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insure_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='max_insured_amount',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='premium',
        ),
    ]
