# Generated by Django 3.2.7 on 2021-09-25 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insure_app', '0002_auto_20210925_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_status', models.CharField(max_length=50)),
                ('policyid', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
