# Generated by Django 3.2.7 on 2021-09-25 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insure_app', '0003_policyhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policyhistory',
            name='policyid',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
